# Generated by Django 3.2 on 2021-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210507_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(),
        ),
    ]
